import { Achievement } from "@/type/achievement.js";

const postAch: Achievement[] = [
  {
    id: 101,
    title: "初次分享",
    description: "发布人生第一条动态，记录属于自己的瞬间",
    type: "SOCIAL",
    condition_logic: "AND",
    conditions: [{ type: "post", count: 1 }],
    rewards: [
      { type: "exp", amount: 10 },
      { type: "coin", amount: 10 },
      { type: "attr", attribute_name: "social", amount: 5 },
    ],
    is_hidden: 0,
    is_active: 1,
  },
  {
    id: 102,
    title: "分享达人",
    description: "累计发布 10 条动态，成为社区活跃分子",
    type: "SOCIAL",
    condition_logic: "AND",
    conditions: [{ type: "post", count: 10 }],
    rewards: [
      { type: "exp", amount: 20 },
      { type: "coin", amount: 20 },
      { type: "attr", attribute_name: "discipline", amount: 10 },
    ],
    is_hidden: 0,
    is_active: 1,
  },
  {
    id: 103,
    title: "生活记录者",
    description: "累计发布 50 条动态，用内容填满时光",
    type: "SOCIAL",
    condition_logic: "AND",
    conditions: [{ type: "post", count: 50 }],
    rewards: [
      { type: "exp", amount: 40 },
      { type: "coin", amount: 40 },
      { type: "attr", attribute_name: "social", amount: 15 },
    ],
    is_hidden: 0,
    is_active: 1,
  },
  {
    id: 104,
    title: "社交风向标",
    description: "累计发布 100 条动态，你的进步被更多人看见",
    type: "SOCIAL",
    condition_logic: "AND",
    conditions: [{ type: "post", count: 100 }],
    rewards: [
      { type: "exp", amount: 60 },
      { type: "coin", amount: 60 },
      { type: "attr", attribute_name: "social", amount: 20 },
    ],
    is_hidden: 0,
    is_active: 1,
  },
  {
    id: 105,
    title: "内容创作者",
    description: "累计发布 500 条动态，成为社区核心分享者",
    type: "TASK",
    condition_logic: "AND",
    conditions: [{ type: "post", count: 500 }],
    rewards: [
      { type: "exp", amount: 100 },
      { type: "coin", amount: 100 },
      { type: "attr", attribute_name: "social", amount: 50 },
    ],
    is_hidden: 0,
    is_active: 1,
  },
];

const likeAch: Achievement[] = [
  {
    id: 201,
    title: "小有共鸣",
    description: "动态累计获得 10 个点赞，你的收获被认可",
    type: "SOCIAL",
    condition_logic: "AND",
    conditions: [{ type: "like", count: 10 }],
    rewards: [
      { type: "exp", amount: 10 },
      { type: "coin", amount: 10 },
      { type: "attr", attribute_name: "social", amount: 10 },
    ],
    is_hidden: 0,
    is_active: 1,
  },
  {
    id: 202,
    title: "人气新星",
    description: "动态累计获得 100 个点赞，收获第一批粉丝",
    type: "SOCIAL",
    condition_logic: "AND",
    conditions: [{ type: "like", count: 100 }],
    rewards: [
      { type: "exp", amount: 20 },
      { type: "coin", amount: 20 },
      { type: "attr", attribute_name: "social", amount: 20 },
    ],
    is_hidden: 0,
    is_active: 1,
  },
  {
    id: 203,
    title: "社区焦点",
    description: "动态累计获得 500 个点赞，成为社区人气担当",
    type: "SOCIAL",
    condition_logic: "AND",
    conditions: [{ type: "like", count: 500 }],
    rewards: [
      { type: "exp", amount: 40 },
      { type: "coin", amount: 40 },
      { type: "attr", attribute_name: "social", amount: 30 },
    ],
    is_hidden: 0,
    is_active: 1,
  },
  {
    id: 204,
    title: "全民喜爱",
    description: "动态累计获得 1000 个点赞，你的成长打动千人",
    type: "SOCIAL",
    condition_logic: "AND",
    conditions: [{ type: "like", count: 1000 }],
    rewards: [
      { type: "exp", amount: 100 },
      { type: "coin", amount: 100 },
      { type: "attr", attribute_name: "social", amount: 50 },
    ],
    is_hidden: 0,
    is_active: 1,
  },
];

export default [...postAch, ...likeAch];
